### ISSUE TITLE
Measures seems unreliable when working with IRQ

### ISSUE THREAD

**Issue by MonsieurV** [MonsieurV/ArduinoPocketGeiger#1]
Working with interrupts on an Arduino Uno seems to give incorrect result when the acquisition runs over a long period of time (more than a couple of minutes).

I've done a series of tests using alternatively:
1. [my fork of the Arduino library with IRQs](https://github.com/MonsieurV/RadiationWatch/blob/8d13438b9abf180ee7ab45a4cda1b5a489c77437/examples/RadiationWatchPrinter/RadiationWatchPrinter.ino#L8), or [the one from Tourmal](https://github.com/Toumal/RadiationWatch)
2. [The Arduino library from thomasaw](https://github.com/thomasaw/RadiationWatch), which is an adaptation of the Radiation Watch Arduino sketch into an Arduino library
3. The very original Arduino sketch from [Radiation Watch sample codes](http://radiation-watch.sakuraweb.com/share/ARDUINO.zip)

The first gives results around `11 nSv/h` after more than, whereas the two others gives measures of ~`50 nSv/h`, with stable results over all the acquisition time. Note that the first one have also results around `50 nSv/h` the first minutes of the acquisition, but after some time the results drops to stabilize around `11 nSv/h`.

The tests were run on the same environnement and over a period of time superior than 20 minutes (knowing that the recommanded acquisition time to have reliable results with the type 5 Radiation Watch is 2 min [see Radiation Watch spec chart](http://www.radiation-watch.org/p/english.html)).

I have no test bench or other counter geiger to validate that the measures are good, but something seems wrong with the Arduino library that uses IRQ.

I'll do tests again with data logging to be able to really compare the results

**Comment by MonsieurV** [comment]
80750d54614d80596ac4b86483a97dfd1351f780 fixed it

**Comment by thomasaw** [comment]
Thanks for tracking down this problem.

**Comment by MonsieurV** [comment]
Hey! While you're here, do you mind if we open-source the library? (for e.g. under a MIT licence)

I think we are far away from the original lib to make this without asking them. But maybe it's better to send Radiation Watch a message before?

**Comment by MonsieurV** [comment]
I have the problem again, the measurements drop after about 15 minutes.

It must be related to [the history management](https://github.com/MonsieurV/ArduinoPocketGeiger/blob/98c02629ddc2404b95638bbf54391c166a4faf8c/RadiationWatch.cpp#L77), but I'm not sure how. I'll track the changes I've made to identify what exactly causes the issue.

Edit: maybe it's an overflow of some variable that causes that? I changed some types to `byte` to slightly reduce the memory footprint in 5d176790574f6b0b684e15575e32e3057aff1354

Edit: To keep up with this, it is clearly not a problem caused by interrupts. At worst it would artificially increase the values as [the timer stops during the ISR](https://github.com/MonsieurV/ArduinoTimeInterruptHell).

---

The issue is not present in these revisions:
- 80750d54614d80596ac4b86483a97dfd1351f780
- 5b29f880f5f39cb4e3e0a5b7006b3ed3163e839d

**Comment by thomasaw** [comment]
I'll look into the licensing issue.

**Comment by MonsieurV** [comment]
Ok, the problem was [here](/MonsieurV/ArduinoPocketGeiger/commit/f9d92b4fcaa73d61196ae87a6303f4f119893999#diff-100ddd02d03174cbb1585a9e56ade489R55).

I simply made an invalid calculation of the history duration.

To allow to change dynamically the history length correctly (see the issue spotted in 80750d54614d80596ac4b86483a97dfd1351f780) I've changed the code to dynamically calculate the history duration after the length of the history array. Each cell of this array stores the count for N seconds, so we only need to make a simple calculation to determine the duration of the history (`duration = duration of a cell * number of cell`).

It is now possible to change the history length by modifying only the value of [the define](/MonsieurV/ArduinoPocketGeiger/blob/82d7ee22c07d424d3bcf6cc4b730eda862867e68/RadiationWatch.h#L15), the following being ajusted accordingly.

I will make the history length an optional argument of the RadiationWatch constructor, because it has a serious impact on the memory footprint. Allowing to reduce the history length will make it possible to run [the SD card data logger](/MonsieurV/ArduinoPocketGeiger/tree/master/examples/SdCardCsvLogger) on an Arduino Uno.

**Comment by MonsieurV** [comment]
This time it's good, all run fine. I've made the `HISTORY_LENGTH` configurable. ab37d3588bfa0c286b2e92e1aa4ef5eaeb4e8b79

@thomasaw Would be cool to have your feedback concerning the licence. You can sent me a message directly (check my profile for my email). :)

**Comment by MonsieurV** [comment]
For the record, before the fix (measurements constantly dropping): ![again_failed_issue_with_historic](https://cloud.githubusercontent.com/assets/1753348/11546025/09ae6198-994b-11e5-8c2f-ef1493ab4b1d.PNG)

After:
![capture](https://cloud.githubusercontent.com/assets/1753348/11546029/0c9ee36e-994b-11e5-92be-70a7b3099d4f.PNG)
