### ISSUE TITLE
Only recieve data when I tap the sensor

### ISSUE THREAD

**Issue by ewan-pugh** [MonsieurV/ArduinoPocketGeiger#13]
Hi,

I am using an Arduino Nano IoT 33 and am experiencing similar behavior to the behavior described in issue 11. I only receive data when I tap the sensor
I am using version 0.6.4 of RadiationWatch install via Arduino libraries.
Could you help with this please?

Thanks,
Ewan

**Comment by MonsieurV** [comment]
Hi @ewan-pugh 

Which pins do you use?

Apparently only the following can be used for interrupts on Nano IoT 33: `2, 3, 9, 10, 11, 13, A1, A5, A7`

Ref https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt/

Potentially related #11

**Comment by ewan-pugh** [comment]
Hi @MonsieurV 

I am using pins 2 and 3

**Comment by MonsieurV** [comment]
Ok, seems good following the doc.

Can we have a dump of the output of a test program?
With [SimpleSerialPrinter](https://github.com/MonsieurV/ArduinoPocketGeiger/blob/master/examples/SimpleSerialPrinter/SimpleSerialPrinter.ino)

Theorically if you have _A wild gamma ray appeared_ (when you tap the sensor) the signal from the radiation pin is working. Maybe this is the sensor or environment. Do you have tested it in another setup?

You may try it first with a simpler sketch that does not rely on interrupts, like the original one from [Radiation-Watch.org](https://cdn.sparkfun.com/assets/learn_tutorials/1/4/3/PocketGeigerArduinoExample.zip) (here hosted on Sparkfun, [the original package with a Windows Monitoring application](radiation-watch.sakuraweb.com/share/PocketGeigerType5_ARDUINO.zip)).

**Comment by ewan-pugh** [comment]
Done some more checking this morning. It was an error on my end, works fine!
Thanks
