### ISSUE TITLE
Add the library to the Arduino Library Manager

### ISSUE THREAD

**Issue by puuu** [MonsieurV/ArduinoPocketGeiger#6]
IMHO it would be nice to integrate this library in the Arduino Library Manager. [Here](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager) is described how to do this. We only need a to write [library.properties](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification) file, create a release tag and open an issue on Arduino's GitHub.

@MonsieurV can you create the `library.properties`? Then, after #5 is closed we can create a release tag.

**Comment by MonsieurV** [comment]
Good idea!

I created a release: [v1.0](https://github.com/MonsieurV/ArduinoPocketGeiger/releases/tag/v1.0)

If all is good for you, we can [open the issue](https://github.com/arduino/Arduino/issues) on Arduino part.

**Comment by puuu** [comment]
> I created a release: v1.0

According to the [FAQ](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ), it must be [semver compliant](http://semver.org/): MAJOR.MINOR.PATCH (three numbers)

I am not yet sure, if we should move to 1.0.0 or start by something like 0.5.0.

**Comment by MonsieurV** [comment]
That's rather arbitrary, but ok, let's be kind of modest: `v0.6.0`.

https://github.com/MonsieurV/ArduinoPocketGeiger/releases/tag/v0.6.0

Good? :)

**Comment by puuu** [comment]
Looks fine. :1st_place_medal: 

Time to open the issue on [Arduino](https://github.com/arduino/Arduino/issues). ;-)

**Comment by MonsieurV** [comment]
Just need to wait a bit now!

https://github.com/arduino/Arduino/issues/6030

**Comment by MonsieurV** [comment]
Wasn't long :)

http://arduinolibraries.info/libraries/radiation-watch
